server.name: "kibana"
server.host: "kibana"
server.ssl.enabled: true
server.ssl.certificate: config/certs/ca/ca.crt
server.ssl.key: config/certs/ca/ca.key
monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"
elasticsearch.ssl.certificateAuthorities: ["config/certs/ca/ca.crt"]
